# -*- coding: utf-8 -*-
"""GLC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eow5eGIhsCTBtdNRksXWcsGYXP78LbAX
"""

import nltk

grammar = nltk.CFG.fromstring("""
    MT -> MS SPS VN SC IN CSS
    CSS -> CS CSS | CS DC
    CS -> CST SPS VN SC IN CD | CST SPS VN SPS SC IN CD | CST SPS NM SC IN CD | CST SPS NM SPS SC IN CD
    DC -> CST SPS US SC IN CD | CST SPS US SPS SC IN CD
    CD -> PNT PR CM EN CMM PL IN | VN SPS EQ SPS NM IN | VN SPS EQ SPS CM EN CMM IN | MT
    EN -> VN | VN SP EN
    VN -> LT VS | US VS | LT | US
    VS -> LT VS | LT | NM VS | NM | US VS | US | EP
    TBS -> TB TBS | TB
    TB -> SP SP SP SP
    IN -> NL TBS
    SPS -> SP SPS | SP
    LT -> "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
    NM -> "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
    MS -> "m" "a" "t" "c" "h"
    CST -> "c" "a" "s" "e"
    PNT -> "p" "r" "i" "n" "t"
    SP -> " "
    SC -> ":" | SPS ":"
    NL -> "~"
    US -> "_"
    EQ -> "=" | SPS "=" SPS
    EP -> ""
    PR -> "("
    PL -> ")"
    CM -> "'"
    CMM -> "'"
""")

# Test the CFG
parser = nltk.ChartParser(grammar)

text = """match _var_name1:
    case 1:
        match varName2:
            case 1:
                match varName2:
                    case 1:
                        var = 'Hola Mundo'
                    case _:
                        print('Adios')
            case _:
                print('Adios')
    case 2:
        var = 'Hola Mundo'
    case 3:
        var = 0
    case _:
        print('Hola Benji')
        """

text = text.replace('\n','~')

for tree in parser.parse([*text]):
    tree.pretty_print()

test_case1 = """match var_1:
    case 1:
        print('Path one')
    case 2:
        print('Path two')
    case _:
        print('Default')
        """

test_case1 = test_case1.replace('\n','~')

for tree in parser.parse([*test_case1]):
    tree.pretty_print()

test_case2 = """match var_2:
    case 1:
        var = 1
    case 2:
        var = 2
    case _:
        var = 3
        """

test_case2 = test_case2.replace('\n','~')

for tree in parser.parse([*test_case2]):
    tree.pretty_print()

test_case3 = """match _varName1:
    case var1:
        match var_2:
            case 1:
                var = 1
            case 2:
                var = 2
            case _:
                var = 3
    case var2:
        var = 2
    case _:
        var = 3
        """

test_case3 = test_case3.replace('\n','~')

for tree in parser.parse([*test_case3]):
    tree.pretty_print()

test_case4 = """match _varName_23:
    case var1:
        match var_2:
            case 1:
                match var_2:
                    case 1:
                        var = 1
                    case _:
                        var = 3
            case _:
                var = 3
    case var2:
        var = 2
    case _:
        var = 3
        """

test_case4 = test_case4.replace('\n','~')

for tree in parser.parse([*test_case4]):
    tree.pretty_print()

test_caseF1 = """match var_1:
    case 1:
        print('Path one')
    case 2:
        print('Path two')
    case 3:
        print('Path three')
        """

test_caseF1 = test_caseF1.replace('\n','~')

for tree in parser.parse([*test_caseF1]):
    tree.pretty_print()

test_caseF2 = """match var_2:
    case 1:
        var = var1
    case 2:
        var = var2
    case _:
        var = var3
        """

test_caseF2 = test_caseF2.replace('\n','~')

for tree in parser.parse([*test_caseF2]):
    tree.pretty_print()

test_caseF3 = """match 1varName:
    case var1:
        match var_2:
            case 1:
                var = 1
            case 2:
                var = 2
            case _:
                var = 3
    case var2:
        var = 2
    case _:
        var = 3
        """

test_caseF3 = test_caseF3.replace('\n','~')

for tree in parser.parse([*test_caseF3]):
    tree.pretty_print()

test_caseF4 = """match _varName_23:
    case var1:
        match var_2:
            case 1:
                match var_2:
                    case 1:
                        var = 1
                    case _:
                        var = 3
            case _:
                var = 3
    case var2:
        print('22')
    case _:
        var = 323
        """

test_caseF4 = test_caseF4.replace('\n','~')

for tree in parser.parse([*test_caseF4]):
    tree.pretty_print()